### ISSUE TITLE
framerate dependent updates

### ISSUE THREAD

**Issue by dannyfritz** [berto/fog-of-war#2]
I have a feeling your computer is a lot faster than mine:

https://www.youtube.com/watch?v=EBP6VqLvgd0

Try to incorporate delta time into your calculations or put a sleep in the main loop to make the frame rate consistent across machines. https://www.construct.net/en/tutorials/delta-time-and-framerate-independence-2

**Comment by bertoort** [comment]
Hi @dannyfritz. I changed the update to use the framerate delta (https://github.com/berto/fog-of-war/blob/master/src/game.rs#L62). Mind giving it a try again?

**Comment by dannyfritz** [comment]
https://www.youtube.com/watch?v=WvO7y0JF80I&feature=youtu.be

**Comment by bertoort** [comment]
It looks like you entered a cheat code. How convenient only the baddies are slow?? It'd be a good power up...

Either way, I think I know what the issue is. I was updating the baddies in the draw method. I thought the function got called right after the update, but that's not the case (ggez doesn't really really explain the lifecycle https://docs.rs/ggez/0.5.0-rc.0/ggez/event/trait.EventHandler.html#required-methods).

It should be fixed now :D

**Comment by dannyfritz** [comment]
The deeper you go into gameloops, the more you realize there is no attachment between when the game renders and when the game updates. http://gameprogrammingpatterns.com/game-loop.html

I'm fairly sure the bug is in one of these 2 lines: https://github.com/berto/fog-of-war/blob/73b1143/src/player.rs#L137-L138

**Comment by dannyfritz** [comment]
Try enabling vsync either through your OS or through GGEZ to see if you can repro the bug.

**Comment by dannyfritz** [comment]
Oh, and in GGEZ's loop, draw is called right after update: https://docs.rs/ggez/0.5.0-rc.0/src/ggez/event.rs.html#253

**Comment by bertoort** [comment]
I like the anticipation of waiting to see if it worked for you. I was thinking of a way to replicate the bug. I added vsync and it didn't seem to change much. I left it just in case.

It should be fixed now :P that line you pointed out definitely had a logic flaw, which led to other minor tweaks.

That article is great. Really makes me want to write a basic game engine. I like how he suggests dealing with lag during the update. GGEZ should do that but yeah, it seems the draw it's called right after

**Comment by dannyfritz** [comment]
Game is challenging now!

**Comment by bertoort** [comment]
haha nice! thanks for all the help. Remember to hit SPACE to boost away!!
